version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: svelte
    versions:
    - 3.32.0
    - 3.32.1
    - 3.32.2
    - 3.32.3
